apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-internal
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/Er3en/homeLab
    targetRevision: HEAD
    path: argo-apps/dev/ingresses/internal
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: ingress-nginx
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
  info:
    - name: depends-on
      value: cert-issuer
