apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ingress-nginx-public
  namespace: argocd
spec:
  destination:
    namespace: ingress-nginx-public
    server: https://kubernetes.default.svc
  project: default
  source:
    repoURL: https://kubernetes.github.io/ingress-nginx
    chart: ingress-nginx
    targetRevision: 4.10.0
    helm:
      values: |
        controller:
          ingressClassResource:
            name: public-nginx
          ingressClass: public-nginx
          service:
            annotations:
              service.beta.kubernetes.io/aws-load-balancer-scheme: internet-facing
              service.beta.kubernetes.io/aws-load-balancer-type: nlb
            type: LoadBalancer
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
